DROP DATABASE IF EXISTS bookrepository;
CREATE DATABASE bookrepository;
USE bookrepository;

CREATE TABLE Users (
UserID 	INT PRIMARY KEY AUTO_INCREMENT,
FirstName VARCHAR(255) NOT NULL,	
LastName VARCHAR(255) NOT NULL,
Emaillogin VARCHAR(255) NOT NULL,
Passwordhash VARCHAR(255) NOT NULL,
AccountMadeDate DATE,
AccountClosingDate DATE
);

CREATE TABLE Authors (
AuthorID INT PRIMARY KEY AUTO_INCREMENT,
FirstName VARCHAR(255) NOT NULL,	
LastName VARCHAR(255) NOT NULL
);

CREATE TABLE Books (
BookID 	INT PRIMARY KEY AUTO_INCREMENT,
Title VARCHAR(255) NOT NULL,	
AuthorID INT NOT NULL,
BookGenreID INT NOT NULL,
ISBN INT NOT NULL,
Pyear INT,
Cost NUMERIC (10,2) NOT NULL,
Length INT NOT NULL
);

CREATE TABLE BookGenre (
BookGenreID INT PRIMARY KEY AUTO_INCREMENT,
GenreName VARCHAR(255) NOT NULL,	
BookID INT NOT NULL
);

CREATE TABLE BooksRead (
BooksReadID INT PRIMARY KEY AUTO_INCREMENT,
 UserID INT NOT NULL ,	
  FOREIGN KEY (UserID) references Users(userID),
 BookID INT NOT NULL,
 FOREIGN KEY (BookID) references Books(BookID),  
DateRead DATE,
ReviewDate DATE,
ReviewText VARCHAR(255) NOT NULL,
Rating INT NOT NULL
);